-- MySQL Script generated by MySQL Workbench
-- Thu Jun 29 19:07:14 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categoria` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(65) NOT NULL,
  `dirección` VARCHAR(60) NOT NULL,
  `cp` INT(5) NOT NULL,
  `localidad` VARCHAR(30) NOT NULL,
  `provincia` VARCHAR(30) NOT NULL,
  `teléfono` INT(9) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`productos` (
  `id_productos` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_producto` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `imagen` BLOB NOT NULL,
  `categoria_id_categoria` INT NULL,
  PRIMARY KEY (`id_productos`),
  INDEX `fk_productos_categoria1_idx` (`categoria_id_categoria` ASC) VISIBLE,
  CONSTRAINT `fk_productos_categoria1`
    FOREIGN KEY (`categoria_id_categoria`)
    REFERENCES `mydb`.`categoria` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tienda` (
  `id_tienda` INT NOT NULL,
  `direccion` VARCHAR(65) NOT NULL,
  `localidad` VARCHAR(20) NOT NULL,
  `cp` INT(5) NOT NULL,
  `provincia` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `id_comanda` INT NOT NULL AUTO_INCREMENT,
  `fecha/hora` DATETIME NOT NULL,
  `precio_total` DECIMAL(6,2) NOT NULL,
  `id_repartidor` INT NOT NULL,
  `fecha_hora_entrega` DATETIME NOT NULL,
  `cliente_id_cliente` INT NOT NULL,
  `tienda_id_tienda` INT NOT NULL,
  `take_away` TINYINT NOT NULL,
  PRIMARY KEY (`id_comanda`, `cliente_id_cliente`, `tienda_id_tienda`),
  INDEX `fk_comanda_cliente_idx` (`cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_comanda_tienda1_idx` (`tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_cliente`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `mydb`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cantidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cantidad` (
  `id_cantidad` INT NOT NULL AUTO_INCREMENT,
  `cantidad` INT NOT NULL,
  `cantidad_pizza` INT NULL,
  `cantidad_hamburguesa` INT NULL,
  `cantidad_bebidas` INT NULL,
  `productos_id_productos` INT NOT NULL,
  `comanda_id_comanda` INT NOT NULL,
  `comanda_cliente_id_cliente` INT NOT NULL,
  `comanda_tienda_id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_cantidad`, `productos_id_productos`, `comanda_id_comanda`, `comanda_cliente_id_cliente`, `comanda_tienda_id_tienda`),
  INDEX `fk_cantidad_productos1_idx` (`productos_id_productos` ASC) VISIBLE,
  INDEX `fk_cantidad_comanda1_idx` (`comanda_id_comanda` ASC, `comanda_cliente_id_cliente` ASC, `comanda_tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_cantidad_productos1`
    FOREIGN KEY (`productos_id_productos`)
    REFERENCES `mydb`.`productos` (`id_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cantidad_comanda1`
    FOREIGN KEY (`comanda_id_comanda` , `comanda_cliente_id_cliente` , `comanda_tienda_id_tienda`)
    REFERENCES `mydb`.`comanda` (`id_comanda` , `cliente_id_cliente` , `tienda_id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`trabajador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`trabajador` (
  `id_trabajador` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(60) NOT NULL,
  `NIF` VARCHAR(9) NOT NULL,
  `teléfono` INT(9) NOT NULL,
  `puesto` TINYINT(2) NOT NULL,
  `tienda_id_tienda` INT NOT NULL,
  PRIMARY KEY (`id_trabajador`, `tienda_id_tienda`),
  INDEX `fk_trabajador_tienda1_idx` (`tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_trabajador_tienda1`
    FOREIGN KEY (`tienda_id_tienda`)
    REFERENCES `mydb`.`tienda` (`id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`entrega_domicilio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`entrega_domicilio` (
  `entrega_domiciliocol` INT NOT NULL AUTO_INCREMENT,
  `hora` DATETIME NOT NULL,
  `comanda_id_comanda` INT NOT NULL,
  `comanda_cliente_id_cliente` INT NOT NULL,
  `trabajador_id_trabajador` INT NOT NULL,
  `trabajador_tienda_id_tienda` INT NOT NULL,
  PRIMARY KEY (`entrega_domiciliocol`, `comanda_id_comanda`, `comanda_cliente_id_cliente`, `trabajador_id_trabajador`, `trabajador_tienda_id_tienda`),
  INDEX `fk_entrega_domicilio_comanda1_idx` (`comanda_id_comanda` ASC, `comanda_cliente_id_cliente` ASC) VISIBLE,
  INDEX `fk_entrega_domicilio_trabajador1_idx` (`trabajador_id_trabajador` ASC, `trabajador_tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_entrega_domicilio_comanda1`
    FOREIGN KEY (`comanda_id_comanda` , `comanda_cliente_id_cliente`)
    REFERENCES `mydb`.`comanda` (`id_comanda` , `cliente_id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_entrega_domicilio_trabajador1`
    FOREIGN KEY (`trabajador_id_trabajador` , `trabajador_tienda_id_tienda`)
    REFERENCES `mydb`.`trabajador` (`id_trabajador` , `tienda_id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda_has_productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda_has_productos` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda_has_productos1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda_has_productos1` (
  `comanda_id_comanda` INT NOT NULL,
  `comanda_cliente_id_cliente` INT NOT NULL,
  `comanda_tienda_id_tienda` INT NOT NULL,
  `productos_id_productos` INT NOT NULL,
  PRIMARY KEY (`comanda_id_comanda`, `comanda_cliente_id_cliente`, `comanda_tienda_id_tienda`, `productos_id_productos`),
  INDEX `fk_comanda_has_productos1_productos1_idx` (`productos_id_productos` ASC) VISIBLE,
  INDEX `fk_comanda_has_productos1_comanda1_idx` (`comanda_id_comanda` ASC, `comanda_cliente_id_cliente` ASC, `comanda_tienda_id_tienda` ASC) VISIBLE,
  CONSTRAINT `fk_comanda_has_productos1_comanda1`
    FOREIGN KEY (`comanda_id_comanda` , `comanda_cliente_id_cliente` , `comanda_tienda_id_tienda`)
    REFERENCES `mydb`.`comanda` (`id_comanda` , `cliente_id_cliente` , `tienda_id_tienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_has_productos1_productos1`
    FOREIGN KEY (`productos_id_productos`)
    REFERENCES `mydb`.`productos` (`id_productos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
