-- MySQL Script generated by MySQL Workbench
-- Thu Jun 29 19:35:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`marca` (
  `id_marca` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`vendedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`vendedor` (
  `id_vendedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`id_vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`clientes` (
  `id_clientes` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `apellidos` VARCHAR(65) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(25) NOT NULL,
  `provincia` VARCHAR(25) NOT NULL,
  `cp` INT(5) NOT NULL,
  `teléfono` INT(9) NOT NULL,
  `emaill` VARCHAR(30) NULL,
  `registro` DATETIME NOT NULL,
  PRIMARY KEY (`id_clientes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ventas` (
  `id_ventas` INT NOT NULL AUTO_INCREMENT,
  `fecha_venta` DATETIME NOT NULL,
  `vendedor_id_vendedor` INT NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`id_ventas`, `vendedor_id_vendedor`, `clientes_id_clientes`),
  INDEX `fk_ventas_vendedor1_idx` (`vendedor_id_vendedor` ASC) VISIBLE,
  INDEX `fk_ventas_clientes1_idx` (`clientes_id_clientes` ASC) VISIBLE,
  CONSTRAINT `fk_ventas_vendedor1`
    FOREIGN KEY (`vendedor_id_vendedor`)
    REFERENCES `mydb`.`vendedor` (`id_vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ventas_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `mydb`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`gafas` (
  `id_gafas` INT NOT NULL AUTO_INCREMENT,
  `montura_tipo('flotante', 'metálicas', 'pasta')` VARCHAR(45) NOT NULL,
  `montura_color` VARCHAR(45) NOT NULL,
  `color_vidrio` ENUM('Polarizadas', 'Ahumadas', 'Azul') NOT NULL,
  `grad_drcho` DECIMAL(2,2) NOT NULL,
  `grad_izdo.` DECIMAL(2,2) NOT NULL,
  `precio` DECIMAL(6,2) NOT NULL,
  `marca_id_marca` INT NOT NULL,
  `ventas_id_ventas` INT NOT NULL,
  `ventas_vendedor_id_vendedor` INT NOT NULL,
  `ventas_clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`id_gafas`, `marca_id_marca`, `ventas_id_ventas`, `ventas_vendedor_id_vendedor`, `ventas_clientes_id_clientes`),
  INDEX `fk_gafas_marca_idx` (`marca_id_marca` ASC) VISIBLE,
  INDEX `fk_gafas_ventas1_idx` (`ventas_id_ventas` ASC, `ventas_vendedor_id_vendedor` ASC, `ventas_clientes_id_clientes` ASC) VISIBLE,
  CONSTRAINT `fk_gafas_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `mydb`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_gafas_ventas1`
    FOREIGN KEY (`ventas_id_ventas` , `ventas_vendedor_id_vendedor` , `ventas_clientes_id_clientes`)
    REFERENCES `mydb`.`ventas` (`id_ventas` , `vendedor_id_vendedor` , `clientes_id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`proveedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`proveedor` (
  `id_proveedor` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `número` INT NOT NULL,
  `piso` INT NOT NULL,
  `puerta` VARCHAR(6) NOT NULL,
  `cp` INT(5) NOT NULL,
  `nif` VARCHAR(9) NOT NULL,
  `teléfono` INT(9) NOT NULL,
  `fax` INT(9) NOT NULL,
  `ciudad` VARCHAR(20) NOT NULL,
  `marca_id_marca` INT NOT NULL,
  `pais` VARCHAR(15) NULL,
  PRIMARY KEY (`id_proveedor`, `marca_id_marca`),
  INDEX `fk_proveedor_marca1_idx` (`marca_id_marca` ASC) VISIBLE,
  CONSTRAINT `fk_proveedor_marca1`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `mydb`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recomendación`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`recomendación` (
  `id_recomendación` INT NOT NULL AUTO_INCREMENT,
  `id_cliente` INT NOT NULL,
  `clientes_id_clientes` INT NOT NULL,
  PRIMARY KEY (`id_recomendación`),
  INDEX `fk_recomendación_clientes1_idx` (`clientes_id_clientes` ASC) VISIBLE,
  CONSTRAINT `fk_recomendación_clientes1`
    FOREIGN KEY (`clientes_id_clientes`)
    REFERENCES `mydb`.`clientes` (`id_clientes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
